[workspace]
members = [
    "rust-core",
    "rust-auth",
    "rust-level",
    "rust-melior",
    "rust-notification",
    "rust-profile",
    "rust-security"
]
default-members = ["rust-melior"]
resolver = "2"

[profile.dev.package.scrypt]
opt-level = 3
