name: Android CI

on:
  push:
    branches:
      - master
      - sit/ci-testing-grounds
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build app
      run: |
        ./gradlew Campfire:build \
          -Dorg.gradle.jvmargs="-Xmx4096M -Dkotlin.daemon.jvm.options=-Xmx4096M"
