name: Continuous Integration

on:
  push:
    branches:
      - master
      - sit/ci-testing-grounds
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
      - name: Build
        run: |
          ./gradlew build \
            -Dorg.gradle.jvmargs="-Xmx4096M -Dkotlin.daemon.jvm.options=-Xmx4096M"
      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: bonfire-debug
          path: Campfire/build/outputs/apk/debug/Campfire-debug.apk

  clippy:
    name: Check clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy
      - name: Check clippy
        run: cargo clippy

  style:
    name: Check style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt
      - name: Check style
        run: cargo +nightly fmt --check
